### ISSUE TITLE
Profile picture uploading

### ISSUE THREAD

**Issue by platelet-app** [platelet-app/platelet#10]
Profile pictures cannot be set by users.

Need to investigate best way to implement with Amplify and develop the front end to allow profile picture uploading.

Amplify has an option to add storage and has premade UI components for displaying and uploading images.

**Comment by duckbytes** [comment]
Most of this has been implemented in master, except that image uploading needs some kind of access control (using Cognito and IAM?) to make sure that users cannot upload profile pictures that aren't theirs.
