### ISSUE TITLE
MCBB - Unable to change user profile photo

### ISSUE THREAD

**Issue by BloodBikeBestie** [platelet-app/platelet#159]
User cannot update their profile photo from the photo originally selected.

The 'Change' button allows a new photo to be selected and framed using the original gridlines, and after selecting 'Done' the replacement image appears to have been saved. However this does not replace the existing image as the header avatar.

**Comment by duckbytes** [comment]
Hey @BloodBikeBestie 

Does the new image show up properly on the user's profile and in the list of users?

If you refresh the page does the picture in the app header change to the proper image?

**Comment by BloodBikeBestie** [comment]
Hi Theo,
When the profile pic was unpopulated, I was able to select a file, crop and
resize then add it as my profile pic.
When I tried to change it to something more appropriate than my cat, I can
select the file and it appears in the frame. I can't resize but it does
move around in what appears to be the old crop frame.
I then finish and the new image remains in the profile window. However the
old pic remains in the top corner of the dashboard even after the page is
refreshed (mobile and iMac browsers).
If I refresh the profile page it reverts back to the original image.
Phil - MCBB

**Comment by duckbytes** [comment]
Thanks Phil. I was able to replicate this so I'll investigate it tomorrow.

**Comment by duckbytes** [comment]
Hey @BloodBikeBestie I pushed an fix up. Let me know if it's still not working for you.

**Comment by BloodBikeBestie** [comment]
Hi Theo,
Thanks.
I need to understand how changes get released to our production server, as
this is the only instance I currently have access to.
I'll discuss with Steve.
Phil

**Comment by BloodBikeBestie** [comment]
Great, I am on the MCBB production and can confirm profile pic can now be
updated.
Thanks
