### ISSUE TITLE
MCBB - Coordinator dashboard displays cached jobs until logout/login refresh

### ISSUE THREAD

**Issue by BloodBikeBestie** [platelet-app/platelet#166]
Controller reports that historic jobs remain on their dashboard with no status updates following handoff to new controller.
The sequence of events in the 4 jobs reviewed is that the controller creates the job but hands over to a new controller before allocating a rider. When returning for next shift the historic job remains on their dashboard as 'New' even though the job has been completed.
Resolved by the controller logging off, then login again. Would be good to force dashboard refresh somehow.

**Comment by duckbytes** [comment]
Thanks for the report.

This bug relates to Amplify issue here https://github.com/aws-amplify/amplify-js/issues/7134

Completed tasks that are older than one week are archived and no longer synced, which means data older than one week might stay on the device and remain stale.

I think the easiest fix is going to be clear local data if the device hasn't synced at least once in the previous week.
