### ISSUE TITLE
MCBB - History/Export date range query returns dataset offset by 1 day

### ISSUE THREAD

**Issue by BloodBikeBestie** [platelet-app/platelet#167]
When querying date range, the returned data is offset to one day earlier than query.
I entered a date range starting 05-Jul, and returned data was from 04-Jul.

**Comment by duckbytes** [comment]
Should be fixed with commit https://github.com/platelet-app/platelet/commit/9f5c3b77a489f9b84ff793ce093c03ecf19b3aeb

It'll be pushed up to live with the next update.
