### ISSUE TITLE
GraphQL - multi-tenanted access support

### ISSUE THREAD

**Issue by platelet-app** [platelet-app/platelet#18]
GraphQL schema does not support multi-tenanted access. The tenants are the individual charities primarily. It might be helpful to build in support for multiple organisations that comprise of multiple groups.

e.g Blood Bike charities > Freewheelers, SERV, etc...

this would allow tenants of certain organisations to collaborate with other groups, provided they are within the same *organisation* umbrella.

**Comment by duckbytes** [comment]
completed with https://github.com/platelet-app/platelet/pull/26
