### ISSUE TITLE
Neaten up the lists of users/vehicles/locations and add filtering

### ISSUE THREAD

**Issue by duckbytes** [platelet-app/platelet#32]
The lists of users/vehicles/locations could be made to look more consistent with each other and a way for the user to filter them and find things more quickly.

Filtering could also search by extra keys like rider responsibility, bike manufacture, or location address line 1.

**Comment by LamVu1** [comment]
I'm interested in working on this issue.

**Comment by LamVu1** [comment]
Is there more detail on the design?

**Comment by duckbytes** [comment]
You can see what it looks like at the moment by navigating to /vehicles /users or /locations

It's mostly the spacing and formatting is a bit inconsistent between the different views. Maybe some extra information could be placed on the cards too, like the label of riderResponsibilty (if present).

The loading skeletons also don't match what the list looks like. I think at the moment it imports a component to show the skeleton, but it might be better to just use the Skeleton component from Material UI directly in the list.

**Comment by duckbytes** [comment]
https://mui.com/components/skeleton/

**Comment by LamVu1** [comment]
Okay, I'll start from here then.

**Comment by LamVu1** [comment]
@duckbytes I've fixed up the css spacing and made the loading skeletons. How would you want the users to filter? Should it be a dropdown or like the filter search on the dashboard? Are there any specific attributes you think are important for these different lists.

**Comment by duckbytes** [comment]
Nice, thanks @LamVu1 

I think a text search is fine. It could filter for matching `name` `displayName` and `riderResponsibility.label`.

**Comment by LamVu1** [comment]
@duckbytes I'm ready to make a pull request but it doesn't seem like I have the permissions.

**Comment by LamVu1** [comment]
Should I have forked the repo?

**Comment by duckbytes** [comment]
Fork is a good way to do it. You could fork it and change the remote URL to the new fork URL. Push your changes up, then open a pull request from your branch on the fork.
