### ISSUE TITLE
Editing a location/user/vehicle profile could be neater

### ISSUE THREAD

**Issue by duckbytes** [platelet-app/platelet#34]
They could be converted to use ClickableTextField enabled on edit mode. Similar to how src/scenes/Task/components/LocationDetailAndSelector.js does it.

**Comment by LamVu1** [comment]
@duckbytes I want to work on this.

**Comment by duckbytes** [comment]
Nice, thank you Lam.

I'm not sure of the best way it should work. It could be worth experimenting with some different methods/styles and see what you think works best.

**Comment by LamVu1** [comment]
> A few more ideas for neatening up the profiles pages:
> 
> * Reverse the Save and Cancel buttons to be in line with the rest of the app

@duckbytes Do you mean to keep the save and cancel buttons; only changing the text field to ClickableTextField? For all location/user/vehicle profile?

**Comment by duckbytes** [comment]
hey @LamVu1 

I think we should keep the save/cancel buttons, after our discussion on Discord. It seems most intuitive to the user to have them.

I would use normal text fields but see if it's possible to enable edit mode without changing the layout too drastically, which it does at the moment.

Another idea could be to use an edit button for each section as it's currently divided (or close to). Something similar to how the task overview works at the moment. This means a less drastic layout change when the user only wants to change one or two things.

For example a user has their name/display name.

Then they have address and contact details.

Then they have roles and rider responsibility.

These sections could be separated by dividers with an edit button for each, which only enables fields for those sections.

Then when the user is finished making changes, click Save or Cancel.
