### ISSUE TITLE
Update mechanism to retrieve latest version when using the service worker

### ISSUE THREAD

**Issue by duckbytes** [platelet-app/platelet#43]
With the service worker enabled the page always uses the cached version even when an update has been pushed.

The app could prompt the user when a new version is available to update the cache.

This would be particularly useful when using as a PWA.

**Comment by c-macn** [comment]
@duckbytes I think I'll pick this one up as a first issue

**Comment by duckbytes** [comment]
👍 thanks @c-macn

**Comment by c-macn** [comment]
@duckbytes Can you give me the correct access for the repo when you get the chance? I have code ready for a PR

**Comment by duckbytes** [comment]
I've invited you for access.
