### ISSUE TITLE
Ability to set rider responsibility per shift

### ISSUE THREAD

**Issue by PaulFreewheelersEVS** [platelet-app/platelet#48]
The rider responsibility is currently set by the rider. For Freewheelers EVS, this represents the shift type that they ride.  Most riders have more than one shift type and it needs to be set for each shift.  It doesn’t work to set this per rider only.  It needs to be set per rider per shift. It would be logical for the coord to be able to do this at the start of a shift.

This information does need to be available for reporting. For example, how many jobs were on the East patch.

**Comment by duckbytes** [comment]
Hi Paul. Would it be enough for the coord to be able to set the responsibility on the user's profile before the shift starts?

**Comment by PaulFreewheelersEVS** [comment]
As long as it’s intuitive that would work.

 

Thanks
Paul

**Comment by duckbytes** [comment]
The rider responsibility can now be set on the user's profile page.
