### ISSUE TITLE
Allow users to change their password

### ISSUE THREAD

**Issue by duckbytes** [platelet-app/platelet#51]
Passwords can only be changed by using the forgot password method. It should be possible to change password from the app itself.

**Comment by Merseybiker** [comment]
Hi Theo.  This is going to become important for MCBB as the number of riders increase.  We need to be able to manage forgotten passwords with either a password reminder and reset email, or (in the short term) at least giving the Admin role the ability to reset a user password to trigger a one-use password and email to the user again.

**Comment by Joetooker95** [comment]
Users can reset their own password already by pressing ‘forgotten password’ on the login screen.Kind regardsJoe TookerOn 15 May 2023, at 10:23, Steve Curtis ***@***.***> wrote:﻿
Hi Theo.  This is going to become important for MCBB as the number of riders increase.  We need to be able to manage forgotten passwords with either a password reminder and reset email, or (in the short term) at least giving the Admin role the ability to reset a user password to trigger a one-use password and email to the user again.
