### ISSUE TITLE
H and B Caller field for name of establishment

### ISSUE THREAD

**Issue by ianphunt58** [platelet-app/platelet#56]
A establishment may call for a task, that comes from and goes to different locations. We need to record the establsihment that makes the request

**Comment by duckbytes** [comment]
There are three places to record contact information at the moment - there are the "caller details" and also contact information against the pick up and delivery locations. The pick up and delivery location contact information is auto-filled from the directory, but it can be changed by the user after.

Does that work for this use case?

**Comment by ianphunt58** [comment]
Not sure it does.

 

For example, I have this:

 

*	Task requested by Luton and Dunstable
*	Task goes from Watford Pharmacy to Bedford Pharmacy
*	Task requested by Joe

 

Is there a place to add all those

 

Ian

**Comment by duckbytes** [comment]
Ah I understand better now. Yes I'm sure an extra field could be added for the establishment name.

**Comment by duckbytes** [comment]
Proposal for a possible solution towards both this issue and #45

Searchable locations directory on the caller screen to search through known establishments:
![Screenshot from 2022-05-06 20-28-33](https://user-images.githubusercontent.com/32309223/167205101-fbc41979-6b69-42a4-9a20-337b88c1abbb.png)
![Screenshot from 2022-05-06 20-28-37](https://user-images.githubusercontent.com/32309223/167205105-66fecb89-95f2-4fdd-8806-7ef93cc7e4ec.png)
On selection, the establishment label is displayed and a toggle "Same as pick up?" appears. The telephone number is auto-filled from the directory.
![Screenshot from 2022-05-06 20-35-56](https://user-images.githubusercontent.com/32309223/167205832-d679a4d0-1eff-4626-82ad-7357e4eb53c7.png)
When Same as pick up? is selected the pick up location is auto-filled with the same details
![Screenshot from 2022-05-06 20-28-58](https://user-images.githubusercontent.com/32309223/167205111-a6e0547c-cc5c-4a4d-93e0-728bd1421973.png)
Move priority to the final step to better fit the flow of a conversation.
![Screenshot from 2022-05-06 20-29-05](https://user-images.githubusercontent.com/32309223/167205113-5471d6f8-84c5-4826-b77b-c16f87f6a1c6.png)

I've also swapped the pick-up/deliver tabs with items tab to better fit the flow of the conversation.

@PaulFreewheelersEVS let me know your thoughts too.

**Comment by PaulFreewheelersEVS** [comment]
This works for me for #45
